import 'package:drift/drift.dart' hide isNull, isNotNull;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:reptrack/persistance/database.dart';
import 'package:sqlite3/sqlite3.dart' as sqlite;
import '../test_helpers.dart';

/// The `CREATE TABLE` statements of schema version 1, as generated by Drift
/// before the timed tables were added.
const _v1Schema = [
  '''CREATE TABLE "exercise_types" ("id" TEXT NOT NULL, "name" TEXT NOT NULL UNIQUE, PRIMARY KEY ("id"))''',
  '''CREATE TABLE "exercises" ("id" TEXT NOT NULL, "name" TEXT NOT NULL UNIQUE, "note" TEXT NULL, "exercise_type_id" TEXT NULL REFERENCES exercise_types (id), PRIMARY KEY ("id"))''',
  '''CREATE TABLE "equipments" ("id" TEXT NOT NULL, "name" TEXT NOT NULL UNIQUE, "icon_name" TEXT NOT NULL UNIQUE, PRIMARY KEY ("id"))''',
  '''CREATE TABLE "muscle_groups" ("id" TEXT NOT NULL, "name" TEXT NOT NULL UNIQUE, PRIMARY KEY ("id"))''',
  '''CREATE TABLE "exercise_muscle_group" ("exercise_id" TEXT NOT NULL REFERENCES exercises (id), "muscle_group_id" TEXT NOT NULL REFERENCES muscle_groups (id), "focus" TEXT NOT NULL, PRIMARY KEY ("exercise_id", "muscle_group_id"))''',
  '''CREATE TABLE "exercise_equipment" ("exercise_id" TEXT NOT NULL REFERENCES exercises (id), "equipment_id" TEXT NOT NULL REFERENCES equipments (id), PRIMARY KEY ("exercise_id", "equipment_id"))''',
  '''CREATE TABLE "programs" ("id" TEXT NOT NULL, "name" TEXT NOT NULL, PRIMARY KEY ("id"))''',
  '''CREATE TABLE "workout_days" ("id" TEXT NOT NULL, "program_id" TEXT NOT NULL REFERENCES programs (id) ON DELETE CASCADE, "day_name" TEXT NOT NULL, "sort_order" INTEGER NOT NULL DEFAULT 0, PRIMARY KEY ("id"))''',
  '''CREATE TABLE "program_strength_exercises" ("id" TEXT NOT NULL, "workout_day_id" TEXT NOT NULL REFERENCES workout_days (id) ON DELETE CASCADE, "equipment_id" TEXT NULL REFERENCES equipments (id) ON DELETE CASCADE, "exercise_id" TEXT NOT NULL REFERENCES exercises (id), "order_in_program" INTEGER NOT NULL DEFAULT 0, "sets_reps" TEXT NOT NULL DEFAULT '[12]', "rest_timer" INTEGER NULL, "weight" REAL NOT NULL DEFAULT 0.0, PRIMARY KEY ("id"))''',
  '''CREATE TABLE "program_cardio_exercises" ("id" TEXT NOT NULL, "workout_day_id" TEXT NOT NULL REFERENCES workout_days (id) ON DELETE CASCADE, "exercise_id" TEXT NOT NULL REFERENCES exercises (id), "order_in_program" INTEGER NOT NULL DEFAULT 0, "seconds" INTEGER NULL, "distance_planned" REAL NULL, "distance_planned_unit" TEXT NOT NULL DEFAULT 'km', PRIMARY KEY ("id"))''',
  '''CREATE TABLE "program_hybrid_exercises" ("id" TEXT NOT NULL, "workout_day_id" TEXT NOT NULL REFERENCES workout_days (id) ON DELETE CASCADE, "equipment_id" TEXT NULL REFERENCES equipments (id) ON DELETE CASCADE, "exercise_id" TEXT NOT NULL REFERENCES exercises (id), "order_in_program" INTEGER NOT NULL DEFAULT 0, "sets_distances" TEXT NOT NULL DEFAULT '[100.0]', "distance_unit" TEXT NOT NULL DEFAULT 'm', "rest_timer" INTEGER NULL, "weight" REAL NOT NULL DEFAULT 0.0, PRIMARY KEY ("id"))''',
  '''CREATE TABLE "workouts" ("id" TEXT NOT NULL, "workout_day_id" TEXT NOT NULL REFERENCES workout_days (id), "date" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', CURRENT_TIMESTAMP) AS INTEGER)), PRIMARY KEY ("id"))''',
  '''CREATE TABLE "workout_strength_sets" ("id" TEXT NOT NULL, "workout_id" TEXT NOT NULL REFERENCES workouts (id) ON DELETE CASCADE, "exercise_id" TEXT NOT NULL REFERENCES exercises (id), "equipment_id" TEXT NULL REFERENCES equipments (id), "reps" INTEGER NOT NULL, "weight" REAL NOT NULL, "set_number" INTEGER NOT NULL, "is_completed" INTEGER NOT NULL DEFAULT 1 CHECK ("is_completed" IN (0, 1)), "date_logged" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', CURRENT_TIMESTAMP) AS INTEGER)), PRIMARY KEY ("id"))''',
  '''CREATE TABLE "workout_cardio_sets" ("id" TEXT NOT NULL, "workout_id" TEXT NOT NULL REFERENCES workouts (id) ON DELETE CASCADE, "exercise_id" TEXT NOT NULL REFERENCES exercises (id), "duration_seconds" INTEGER NOT NULL, "distance_meters" REAL NULL, "distance_unit" TEXT NOT NULL DEFAULT 'km', "is_completed" INTEGER NOT NULL DEFAULT 1 CHECK ("is_completed" IN (0, 1)), "date_logged" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', CURRENT_TIMESTAMP) AS INTEGER)), PRIMARY KEY ("id"))''',
  '''CREATE TABLE "workout_hybrid_sets" ("id" TEXT NOT NULL, "workout_id" TEXT NOT NULL REFERENCES workouts (id) ON DELETE CASCADE, "exercise_id" TEXT NOT NULL REFERENCES exercises (id), "equipment_id" TEXT NULL REFERENCES equipments (id), "set_number" INTEGER NOT NULL, "weight" REAL NOT NULL, "distance" REAL NOT NULL, "distance_unit" TEXT NOT NULL DEFAULT 'm', "distance_meters" REAL NULL, "is_completed" INTEGER NOT NULL DEFAULT 1 CHECK ("is_completed" IN (0, 1)), "date_logged" INTEGER NOT NULL DEFAULT (CAST(strftime('%s', CURRENT_TIMESTAMP) AS INTEGER)), PRIMARY KEY ("id"))''',
  '''CREATE TABLE "bodyweight_entries" ("id" TEXT NOT NULL, "date" INTEGER NOT NULL, "weight" REAL NOT NULL, PRIMARY KEY ("id"))''',
];

/// Unix timestamp in seconds for day [day] of January 2024.
int _jan(int day) => DateTime(2024, 1, day).millisecondsSinceEpoch ~/ 1000;

/// Creates the v1 tables in [raw], inserts [seed] rows and marks the file as
/// schema version 1.
void _buildV1(sqlite.Database raw, List<String> seed) {
  for (final stmt in _v1Schema) {
    raw.execute(stmt);
  }
  for (final stmt in seed) {
    raw.execute(stmt);
  }
  raw.execute('PRAGMA user_version = 1');
}

/// Opens an [AppDatabase] on an in-memory v1 database containing [seed].
AppDatabase _openV1(List<String> seed) => AppDatabase.forTesting(
  NativeDatabase.memory(setup: (raw) => _buildV1(raw, seed)),
);

/// v1 rows covering hold exercises, a weighted hold, non-hold exercises, an
/// unlogged set and a program day.
final _seed = [
  "INSERT INTO exercise_types VALUES ('1','Strength'),('2','Cardio'),('3','Hybrid')",
  "INSERT INTO exercises (id, name, exercise_type_id) VALUES "
      "('plank','Plank','1'),('wall','Wall Sit','1'),"
      "('curl','Isometric Curl Hold','1'),('bench','Bench Press','1'),"
      "('row','Plank Row','1')",
  "INSERT INTO programs VALUES ('prog','Core')",
  "INSERT INTO workout_days VALUES ('day','prog','Day A',0)",
  "INSERT INTO workouts VALUES ('w1','day',${_jan(5)})",
  "INSERT INTO workout_strength_sets VALUES "
      "('p1','w1','plank','1',45,0.0,1,1,${_jan(5)}),"
      "('p2','w1','plank','1',45,0.0,2,1,${_jan(5)}),"
      "('p3','w1','plank','1',45,0.0,3,1,${_jan(5)}),"
      "('p4','w1','plank','1',30,0.0,4,0,${_jan(5)}),"
      "('ws','w1','wall','1',30,20.0,1,1,${_jan(5)}),"
      "('b1','w1','bench','2',8,80.0,1,1,${_jan(5)}),"
      "('b2','w1','bench','2',8,82.5,2,1,${_jan(5)}),"
      "('r1','w1','row','3',10,12.5,1,1,${_jan(5)})",
  "INSERT INTO program_strength_exercises VALUES "
      "('pe-bench','day','2','bench',0,'[8,8,8]',120,80.0),"
      "('pe-plank','day','1','plank',2,'[30,30,30]',60,0.0)",
];

void main() {
  setUpAll(setupTestSqlite);

  group('Migration v1 → v2', () {
    late AppDatabase db;

    setUp(() => db = _openV1(_seed));

    tearDown(() => db.close());

    Future<Exercise> exercise(String id) =>
        (db.select(db.exercises)..where((e) => e.id.equals(id))).getSingle();

    Future<List<WorkoutTimedSet>> timedSetsOf(String exerciseId) =>
        (db.select(db.workoutTimedSets)
              ..where((s) => s.exerciseId.equals(exerciseId))
              ..orderBy([(s) => OrderingTerm(expression: s.setNumber)]))
            .get();

    Future<List<WorkoutStrengthSet>> strengthSetsOf(String exerciseId) =>
        (db.select(db.workoutStrengthSets)
              ..where((s) => s.exerciseId.equals(exerciseId))
              ..orderBy([(s) => OrderingTerm(expression: s.setNumber)]))
            .get();

    test('adds the Timed exercise type', () async {
      final types = await db.select(db.exerciseTypes).get();
      expect(
        {for (final t in types) t.id: t.name},
        {'1': 'Strength', '2': 'Cardio', '3': 'Hybrid', '4': 'Timed'},
      );
    });

    test('retypes only the hold exercises', () async {
      expect((await exercise('plank')).exerciseTypeId, '4');
      expect((await exercise('wall')).exerciseTypeId, '4');
      expect((await exercise('curl')).exerciseTypeId, '4');
      expect((await exercise('bench')).exerciseTypeId, '1');
      expect((await exercise('row')).exerciseTypeId, '1');
    });

    test('moves hold sets to timed sets with no time recorded', () async {
      final sets = await timedSetsOf('plank');
      expect(sets.map((s) => s.id), ['p1', 'p2', 'p3', 'p4']);
      expect(sets.map((s) => s.setNumber), [1, 2, 3, 4]);
      expect(sets.map((s) => s.isCompleted), [true, true, true, false]);
      expect(sets.every((s) => s.durationSeconds == 0), isTrue);
      expect(sets.every((s) => s.weight == null), isTrue);
      expect(sets.every((s) => s.workoutId == 'w1'), isTrue);
      expect(sets.every((s) => s.equipmentId == '1'), isTrue);
      expect(sets.first.dateLogged, DateTime(2024, 1, 5));
    });

    test('keeps a weight above 0 kg', () async {
      final sets = await timedSetsOf('wall');
      expect(sets.single.weight, 20.0);
      expect(sets.single.durationSeconds, 0);
    });

    test('removes the converted strength sets and program entries', () async {
      expect(await strengthSetsOf('plank'), isEmpty);
      expect(await strengthSetsOf('wall'), isEmpty);
      final plankEntries = await (db.select(
        db.programStrengthExercises,
      )..where((p) => p.exerciseId.equals('plank'))).get();
      expect(plankEntries, isEmpty);
    });

    test('converts the program entry keeping order and rest', () async {
      final entry = await db.select(db.programTimedExercises).getSingle();
      expect(entry.id, 'pe-plank');
      expect(entry.workoutDayId, 'day');
      expect(entry.exerciseId, 'plank');
      expect(entry.equipmentId, '1');
      expect(entry.orderInProgram, 2);
      expect(entry.restTimer, 60);
      expect(entry.setsSeconds, '[0,0,0]');
    });

    test('leaves non-hold rows unchanged', () async {
      final bench = await strengthSetsOf('bench');
      expect(bench.map((s) => (s.id, s.reps, s.weight, s.setNumber)), [
        ('b1', 8, 80.0, 1),
        ('b2', 8, 82.5, 2),
      ]);
      final row = await strengthSetsOf('row');
      expect(row.single.reps, 10);
      expect(row.single.weight, 12.5);
      final benchEntry = await (db.select(
        db.programStrengthExercises,
      )..where((p) => p.exerciseId.equals('bench'))).getSingle();
      expect(benchEntry.setsReps, '[8,8,8]');
      expect(benchEntry.orderInProgram, 0);
      expect(benchEntry.restTimer, 120);
      expect(benchEntry.weight, 80.0);
    });

    test('keeps the number of sets per workout', () async {
      final strength = await db.select(db.workoutStrengthSets).get();
      final timed = await db.select(db.workoutTimedSets).get();
      expect(strength.length + timed.length, 8);
    });

    test('shows the converted entry in the program stream', () async {
      final days = await db.watchWorkoutDaysWithExercises('prog').first;
      final exercises = days.single.exercises;
      expect(exercises.map((e) => e.exercise.id), ['bench', 'plank']);
      expect(exercises.last.isTimed, isTrue);
      expect(exercises.last.volume.setsSecondsLabel, '3 sets');
    });
  });

  group('Migration v1 → v2 name matching', () {
    test('matches names case-insensitively and skips renamed ones', () async {
      final db = _openV1([
        "INSERT INTO exercises (id, name, exercise_type_id) VALUES "
            "('lower','plank','1'),('renamed','My Plank','1')",
      ]);
      addTearDown(db.close);
      final rows = await db.select(db.exercises).get();
      final types = {for (final e in rows) e.id: e.exerciseTypeId};
      expect(types['lower'], '4');
      expect(types['renamed'], '1');
    });

    test('an empty v1 database upgrades cleanly', () async {
      final db = _openV1([]);
      addTearDown(db.close);
      expect(await db.select(db.workoutTimedSets).get(), isEmpty);
      expect((await db.select(db.exerciseTypes).get()).map((t) => t.id), ['4']);
    });
  });
}
